#!/bin/bash

curl \
	-H "Content-Type: application/json" \
	-H "Authorization: Bearer ${AUTH_TOKEN}" \
	--request PUT \
	--data '{"participantIds":["one","two"]}' \
	https://nuc.emsemble.com:8443/rx/api/v1/admin/outreach/provider/campaign/$CAMPAIGN_ID/execution/ivr
