#!/bin/bash

curl \
	-H "Content-Type: application/json" \
	-H "Authorization: Bearer ${AUTH_TOKEN}" \
	--request POST \
	--data '{"name":"FluCampaign","description":"Flu campaign","beginDate":1565173436897,"endDate":1565259836897}' \
	https://nuc.emsemble.com:8443/rx/api/v1/admin/outreach/provider/campaign
