#!/bin/bash

export CAMPAIGN_ID=`./getCampaignByName "Patient%20enrolment%20campaign"|jq ._id|tr -d '"'`
export CONTAINER_ID=$2
export JWT=`./signIn`

curl -v \
	-H "Content-Type: application/json" \
	-H "Authorization: Bearer $JWT" \
	http://srini.kencorhealth.com:6060/api/campaign/$CAMPAIGN_ID/file/$1 --output /tmp/x.pdf

