#!/bin/bash

export CAMPAIGN_ID=`./getCampaignByName "Patient%20enrolment%20campaign"|jq ._id|tr -d '"'`
export JWT=`./signIn`

curl \
	--form 'file=@/tmp/signature.png' \
	-H "Content-Type: multipart/form-data" \
	-H "Authorization: Bearer $JWT" \
	http://localhost:6060/api/campaign/$CAMPAIGN_ID/file

