#!/bin/bash

export CAMPAIGN_ID=`./getCampaignByName "Patient%20enrolment%20campaign"|jq ._id|tr -d '"'`

export JWT=`./signIn`

curl \
	--request POST \
	-H "Content-Type: application/json" \
	-H "Authorization: Bearer $JWT" \
	http://srini.kencorhealth.com:6060/api/campaign/$CAMPAIGN_ID/nav/$TERMS_NAV_ID?containerId=$CONTAINER_ID \
	--data @<(cat <<EOF
{
  "fileId": "$FILE_ID"
  }
EOF
)
